spring:
  application:
    name: backend-java
  datasource:
    url: jdbc:sqlite:../snazzycrm.db
    #    username: sa
    #    password: sa
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
