#spring:
#  datasource:
#    url: jdbc:h2:~/test
##    username: sq
##    password:
#    driver-class-name: org.hibernate.dialect.H2Dialect
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
##  h2:
##    console:
##      enabled: true
##      path: /h2-ui
#  sql:
#    init:
#      mode: always
##  sql:
##    init:
##      data-locations:
##        - 'classpath:schema.sql'